// @ts-check
// Flat config (ESLint 10). `defineConfig()` is ESLint core's own helper (the non-deprecated replacement for
// typescript-eslint's `tseslint.config()`); it accepts the same per-block `extends` shorthand.
//
// Scope, by what runs where:
//   src/lib/**/*.ts        mounted via <script> into pages: runs in the BROWSER
//   src/**/*.ts (the rest) config, i18n, the content schema: read at build time (Node), some also imported
//                           by src/lib/*.ts, so browser globals are allowed there too
//   **/*.astro              frontmatter runs at build time (Node); its inline <script> runs in the browser
//   scripts/, workers/, and the root tool configs: Node (or the Workers runtime, close enough for globals)
//                           — never bundled for the browser
//   features/**/*.js        Node (Cucumber), but many step definitions hand a callback to Playwright's
//                           `page.evaluate()`/`addInitScript()` that is serialized and run IN THE BROWSER, so
//                           both global sets are allowed here too, same reasoning as .astro
//
// Only correctness rules (each preset's own "recommended"): no stylistic/formatting rules, so this doesn't
// relitigate the codebase's existing, deliberate style.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import astro from 'eslint-plugin-astro';
import globals from 'globals';
import { defineConfig } from 'eslint/config';

// This codebase's own convention (already used throughout, e.g. `const { camera: _empty, ...rest } = data`):
// a leading underscore marks a binding as intentionally unused, and destructuring to omit a key (`{ x, ...rest }`)
// doesn't need one either.
const unusedVarsOptions = { args: 'all', argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_', ignoreRestSiblings: true };

export default defineConfig(
  {
    ignores: [
      '**/dist/',
      '**/dist-prod/',
      '**/.astro/',
      '**/.wrangler/', // wrangler's own build cache (e.g. workers/results-api/.wrangler/tmp/): bundled output, not source
      '**/.photo-entries/',
      '**/test-results/',
      'worker-configuration.d.ts', // generated by `wrangler types`; see tsconfig.json for why it's excluded there too
    ],
  },

  js.configs.recommended,
  { rules: { 'no-unused-vars': ['error', unusedVarsOptions] } },

  {
    files: ['src/lib/**/*.ts'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', unusedVarsOptions],
      // The codebase's own compact style for a two-branch side-effecting choice, e.g.
      // `cond ? a.doThing() : b.doOtherThing();` used as a statement (src/lib/admin-common.ts).
      '@typescript-eslint/no-unused-expressions': ['error', { allowTernary: true }],
    },
  },
  {
    files: ['src/**/*.ts'],
    ignores: ['src/lib/**/*.ts'],
    extends: [tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': ['error', unusedVarsOptions],
      '@typescript-eslint/no-unused-expressions': ['error', { allowTernary: true }],
    },
  },

  ...astro.configs.recommended,
  {
    files: ['**/*.astro'],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
    },
  },

  {
    files: ['scripts/**/*.mjs', 'workers/**/*.mjs', 'test-fixtures/**/*.{js,mjs}', 'astro.config.mjs', 'cucumber.js', 'eslint.config.mjs'],
    languageOptions: {
      globals: globals.node,
      sourceType: 'module',
      ecmaVersion: 'latest',
    },
  },
  {
    files: ['features/**/*.js'],
    languageOptions: {
      globals: { ...globals.node, ...globals.browser },
      sourceType: 'module',
      ecmaVersion: 'latest',
    },
  },
);
